### ISSUE TITLE
Change output directory

### ISSUE THREAD

**Issue by kevinyjiang** [JazzCore/python-pdfkit#114] opened 2018-09-22 15:30 UTC
Hi all, is there any way to specify a specific directory to output the PDFs to? I supposed you could just move them afterwards but it would be nice to export them directly to another directory.

I tried pdfkit.from_string(output, "./pdfs/out.pdf", options=options) but get this error:

```
File "cpa-ui.py", line 100, in generate_docs
    self.modelToPDFConverter.createInvoice(model)
  File "/Users/kevinjiang/projects/cpa-automate/ModelToPDFConverter.py", line 42, in createInvoice
    pdfkit.from_string(output, filename, options=options, css=self.css)
  File "/usr/local/lib/python3.7/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/usr/local/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Loading pages (1/6)
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination                              
Exit with code 1, due to unknown error.
```

Thanks in advance!

**Comment by AcckiyGerman** [comment] 2018-12-13 12:36
`pdfkit.from_string(output, "PATH/TO/FOLDER/WHERE/YOU/CAN/WRITE/RIGHTS/out.pdf", options=options)`
Are you really studying in the University of Columbia? If so, I won't recommend my kids to go there.

Please, close the Issue.

**Comment by citrusvanilla** [comment] 2020-08-03 03:07
@AcckiyGerman It's "Columbia University" you dick.

**Comment by citrusvanilla** [comment] 2020-08-03 03:16
the documentation should specify the "file" argument can be an absolute path.

**Comment by AcckiyGerman** [comment] 2020-08-03 08:01
Oh, sorry @columbia, I actually wanted to insult the guy's "senior" ego, nothing more.

When such a "senior" comes to the interview and can't write FuzzBuzz, what do you do then?
Stroke his head and give him a higher position?

**Comment by AcckiyGerman** [comment] 2020-08-03 08:04
> the documentation should specify the "file" argument can be an absolute path.

This is not a secret for anybody, who ever wrote `open()` in python.

**Comment by JazzCore** [comment] 2021-03-19 19:52
I dont feel a need to specify that paths can be both relative or absolute, it's a default behavior in almost any library. If it was only relative OR absolute - sure, this needs to be specified in README, closing since the issue is answered.

Sorry that it took so long for me to get to it...

**Closed by JazzCore** 2021-03-19 19:52 UTC
