### ISSUE TITLE
something wrong happens when i make pdf from html

### ISSUE THREAD

**Issue by 52lemon** [JazzCore/python-pdfkit#124] opened 2018-12-17 08:03 UTC
`
pdfkit.from_string(html, "static/张三丰的记账凭证FS10001.pdf", configuration=config)
`
error log
`
ERROR:E:\PycharmProjects\ChunJun\apps\v1_5\order\api.py:order_detail_handler in root Traceback (most recent call last):
  File "E:\PycharmProjects\ChunJun\apps\v1_5\order\api.py", line 246, in post_certificate
    pdfkit.from_string(html, file_name, configuration=config)
  File "C:\Python27\lib\site-packages\pdfkit\api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "C:\Python27\lib\site-packages\pdfkit\pdfkit.py", line 129, in to_pdf
    stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 599, in _execute_child
    args = list2cmdline(args)
  File "C:\Python27\lib\subprocess.py", line 294, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 0: unexpected end of data
`
this seems it does not well support chinese characters,how can i solve this problem, can u give me a hand

**Comment by JazzCore** [comment] 2021-03-19 20:01
Should be fixed in master now, looks like a duplicate of #42

**Closed by JazzCore** 2021-03-19 20:01 UTC
