### ISSUE TITLE
wkhtmltopdf path encoding problems in python2 when not using UTF-8

### ISSUE THREAD

**Issue by ankaan** [JazzCore/python-pdfkit#101] opened 2018-04-20 15:52 UTC
When running the following on Windows (wkhtmltopdf is of type unicode and contains a file path containing åäö etc.):

    def topdf(html):

        wkconf = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf)
        r = pdfkit.PDFKit(html, 'string', configuration=wkconf)
        return r.to_pdf(False)

Which is what `from_string` does, i get the following error on windows where `locale.getpreferredencoding() != 'UTF-8'`.

> Traceback (most recent call last):
>   File "salesreport.py", line 291, in <module>
>     convert(sales, stock, pdf, html)
>   File "salesreport.py", line 162, in convert
>     pdfdata = topdf(html)
>   File "salesreport.py", line 172, in topdf
>     r = pdfkit.PDFKit(html, 'string', configuration=wkconf)
>   File "C:\Program Files\Python27\lib\site-packages\pdfkit\pdfkit.py", line 45, in __init__
>     self.wkhtmltopdf = self.configuration.wkhtmltopdf.decode('utf-8')
>   File "C:\Program Files\Python27\lib\encodings\utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 28: ordinal not in range(128)

I then instead tried sending in a UTF-8 encoded string:

    def topdf(html):
        wkconf = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf)
        r = pdfkit.PDFKit(html.encode('utf-8'), 'string', configuration=wkconf)
        return r.to_pdf(False)

I get the the same error.

I found a workaround that is an ugly hack that works:

    def topdf(html):
        wkconf = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf)
        wkconf.wkhtmltopdf = wkconf.wkhtmltopdf.encode('utf-8')
        r = pdfkit.PDFKit(html, 'string', configuration=wkconf)
        r.wkhtmltopdf = wkconf.wkhtmltopdf.decode('utf-8').encode(locale.getpreferredencoding())
        return r.to_pdf(False)

Because:

- Configuration object works best with unicode string input. Otherwise output is garbled when wkhtmltopdf is not found for a path that includes special characters.
- `PDFKit.__init__` expects the path to be a string with UTF-8 encoding when running python2:

        try:
            self.wkhtmltopdf = self.configuration.wkhtmltopdf.decode('utf-8')
        except AttributeError:
            self.wkhtmltopdf = self.configuration.wkhtmltopdf

- Popen in `PDFKit.to_pdf` only works if the path is encoded with the preferred encoding of the system.

So the different parts of pdfkit expects the path to be encoded differently.

I encountered these problems on Windows, but I expect it to be the same on other systems that does not use UTF-8.

**Comment by JazzCore** [comment] 2021-03-19 19:41
Should be fixed now in master, duplicate of #42

Sorry that it took so long for me to get to it...

**Closed by JazzCore** 2021-03-19 19:41 UTC
