### ISSUE TITLE
toc

### ISSUE THREAD

**Issue by yishairasowsky** [JazzCore/python-pdfkit#200] opened 2021-08-14 21:00 UTC
Hi @amandasaurus @EdwardBetts @lexhung @yohanboniface @alanhamlett 
I am a Python developer, and I am beginner at using wkhtmltopdf, and currently I have a html being converted into a pdf. But I want to automatically include a table of contents. The documentation says I should put a file called toc.xsl into the param toc. But I am not familiar with .xsl files, so I am not sure what that file should contain. I looked online for examples, but I think they are a little beyond me. Can you please help guide me? Thanks!

**Comment by yishairasowsky** [comment] 2021-09-11 21:24
please can you tell me how to use the table of contents maker? i do not know how to use .xslfiles. thatnks!

**Comment by yishaistreamline** [comment] 2021-09-23 10:01
is there any update on this? @

**Comment by JazzCore** [comment] 2021-11-14 19:42
This looks like a duplicate of #207, please check the answer I gave there, feel free to repoen if problem persists. But since this is more wkhtmltopdf question and pdfkit only wraps it - you better to try asking for support on https://github.com/wkhtmltopdf/wkhtmltopdf

**Closed by JazzCore** 2021-11-14 19:42 UTC
